name: Bug report
description: Report a problem in a repo that uses the org defaults
labels: [bug]
title: "[Bug]: <short title>"
body:
  - type: checkboxes
    id: preflight
    attributes:
      label: Pre-flight
      options:
        - label: I searched existing issues and PRs
          required: true
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: Steps to reproduce, expected vs actual behavior
      placeholder: "1) … 2) … 3) …"
    validations:
      required: true
  - type: input
    id: repo
    attributes:
      label: Repository
      placeholder: emeraldindustries/<repo>
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: "macOS 14.5 / Ubuntu 22.04, bash 5.2, git 2.44"
  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      render: shell
