name: Feature request
description: Suggest a small, focused improvement
labels: [enhancement]
title: "[Feature]: <short title>"
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem would this improvement solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What’s the minimal change that helps?
      placeholder: "Add --dry-run to X…"
  - type: checkboxes
    id: scope
    attributes:
      label: Scope
      options:
        - label: No external dependencies required
        - label: Keeps behavior backward compatible
