name: Sync org labels
on:
  push:
    paths: [labels.yml, .github/workflows/sync-labels.yml]
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  issues: write
  pull-requests: write
jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: labels.yml
          skip-delete: true
