blank_issues_enabled: false
contact_links:
  - name: Q&A (Emerald Attic Discussions)
    url: https://github.com/emeraldindustries/attic/discussions/categories/q-a
    about: Questions or troubleshooting about one-off utilities.
  - name: Security policy
    url: https://github.com/emeraldindustries/.github/blob/main/SECURITY.md
    about: Please review our security guidance before reporting.
