name: Mark stale issues and PRs
on:
  schedule:
    - cron: '30 1 * * *'
permissions:
  issues: write
  pull-requests: write
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 60
          days-before-close: 14
          stale-issue-label: stale
          stale-pr-label: stale
          exempt-issue-labels: security
          repo-token: ${{ secrets.GITHUB_TOKEN }}
